#!/bin/bash
git init
git add ProjetTutoreEntrepriseRecrute
git add copy
git add upload
git commit -m "first commit"
git remote add origin https://github.com/Yseriu/ProjetTutoreEntrepriseRecrute.git
git push -u origin master